const WISHLIST_ROOMS = [
  { name: "Garage / Storage", icon: "", items: [
    "Screwdriver set (flathead and Phillips)",
    "Power drill bit set",
    "Level",
    "Stud finder",
    "Utility knife",
    "Adjustable wrench",
    "Pliers (needle-nose and regular)",
    "Hex key / Allen wrench set",
    "Rubber mallet",
    "Hand saw",
    "Hacksaw",
    "Pry bar",
    "Caulking gun",
    "Putty knife",
    "Staple gun",
    "Wire stripper",
    "Voltage tester",
    "Extension cord (big)",
    "Ladder (6 ft step)",
    "Wheelbarrow",
    "Shovel",
    "Rake",
    "Broom (outdoor)",
    "Snow shovel",
    "Ice scraper",
    "Garden hose and nozzle",
    "Weed trimmer",
    "Leaf blower",
    "Shop vacuum (wet/dry vac)",
    "Workbench or table",
    "Wood glue",
    "Super glue",
    "Picture hanging hardware",
    "Toolbox",
    "Storage bins with lids",
    "Label maker",
    "Fire extinguisher",
    "First aid kit"
  ]},
  { name: "Kitchen", icon: "", items: [
    "Box grater",
    "Microplane",
    "Silicone Tongs",
    "Slotted spoon",
    "Potato masher",
    "Kitchen shears",
    "Dutch oven",
    "Oven mitts (2 pairs)",
    "Dish towels (6+)",
    "Blendtec blender",
  ]},
  { name: "Living Room", icon: "", items: [
    "Mesh wifi system",
    "Coasters",
    "Wall art",
    "Clock",
  ]},
  { name: "Bedroom", icon: "", items: [
    "Bed frame",
    "Mattress",
    "Mattress protector",
    "Pillows (2 per person)",
    "Pillowcases",
    "Flat sheet",
    "Fitted sheet",
    "Duvet or comforter",
    "Duvet cover",
    "Extra blanket",
    "Nightstands",
    "Nightstand lamp",
    "Dresser or chest of drawers",
    "Full-length mirror",
    "Extension cord with USB ports",
  ]},
  { name: "Bathroom", icon: "", items: [
    "Bath mat",
    "Waterproof foot stool (for shower)",
  ]},
  { name: "Home Office / Guest Room", icon: "", items: [
    "Desk chair (ergonomic)",
    "Cable management clips",
    "Printer (used please)",
    "Printer paper",
    "Ink cartridges",
    "Highlighters",
    "Tape and dispenser",
    "Stapler",
    "Sticky notes",
    "Notepad",
    "Paper clips and binder clips",
    "Power strip with USB",
    "Surge protector",
    "Shredder",
    "Bookends",  
  ]},
  { name: "Laundry Room / Utility", icon: "", items: [
    "Stain remover stick (OxiClean gel stick only)",
    "Drying rack",
    "Iron",
    "Ironing board",
    "Clothespins",
    "Vacuum cleaner (canister vacuum)",
  ]},
  { name: "Outdoor / Yard", icon: "", items: [
    "Kiddie pool",
    "Outdoor furniture (table and chairs)",
    "Outdoor umbrella",
    "Grill (gas)",
    "Grill tools (tongs, brush, spatula)",
    "Grill cover",
    "Propane",
    "Outdoor lighting",
    "String lights",
    "Motion-sensor lights",
    "Outdoor rug",
  ]},
  { name: "Entryway / Mudroom", icon: "", items: [
    "Key hooks or key bowl",
    "Shoe rack and/or mat",
    "Coat hooks or rack",
  ]},
];