const WISHLIST_ROOMS = [
  { name: "Kitchen", icon: "🍳", items: [
    "Chef's knife",
    "Cutting boards (at least 2)",
    "10-inch skillet (non-stick)",
    "Saucepan (2 qt)",
    "Stockpot (8 qt)",
    "Mixing bowls (set)",
    "Measuring cups and spoons",
    "Dish towels (6+)",
    "Storage containers (set)",
    "Coffee maker or kettle"
  ]},
  { name: "Living Room", icon: "🛋️", items: [
    "Sofa",
    "Coffee table",
    "Area rug",
    "Floor lamp",
    "Throw pillows and blanket",
    "Curtains or blinds",
    "Bookshelf",
    "Wall art",
    "Surge protector / power strip",
    "Coasters"
  ]},
  { name: "Bedroom", icon: "🛏️", items: [
    "Bed frame",
    "Mattress",
    "Mattress protector",
    "Duvet or comforter",
    "Pillows (2+)",
    "Fitted and flat sheets",
    "Nightstand",
    "Dresser or chest of drawers",
    "Blackout curtains",
    "Hamper"
  ]},
  { name: "Bathroom", icon: "🚿", items: [
    "Bath towels (2-3)",
    "Hand towels (2-3)",
    "Bath mat",
    "Shower caddy or shelving",
    "Toilet brush and holder",
    "Plunger",
    "First aid kit",
    "Hair dryer",
    "Towel hooks or rack",
    "Drain hair catcher"
  ]},
  { name: "Home Office / Guest Room", icon: "💻", items: [
    "Desk",
    "Desk chair (ergonomic)",
    "Desk lamp",
    "Printer",
    "Filing cabinet or document box",
    "Power strip with USB",
    "Surge protector",
    "Whiteboard or corkboard",
    "Storage bins",
    "Headset or speakers"
  ]},
  { name: "Garage / Storage", icon: "🔧", items: [
    "Hammer",
    "Tape measure (25 ft)",
    "Screwdriver set (flathead + Phillips)",
    "Power drill + bit set",
    "Level",
    "Stud finder",
    "Ladder (6 ft step)",
    "Shop vacuum (wet/dry vac)",
    "Toolbox",
    "Spare light bulbs (LED)"
  ]},
  { name: "Laundry Room / Utility", icon: "🧺", items: [
    "Laundry detergent",
    "Laundry baskets (2+)",
    "Drying rack",
    "Iron and ironing board",
    "Vacuum cleaner",
    "Mop and bucket",
    "All-purpose cleaner",
    "Microfiber cloths",
    "Garbage bags (multiple sizes)",
    "Step stool"
  ]},
  { name: "Outdoor / Yard", icon: "🌿", items: [
    "Welcome mat (front and back)",
    "Outdoor furniture (table + chairs)",
    "Grill (gas or charcoal)",
    "Garden hose + nozzle",
    "Shovel",
    "Rake",
    "Garden gloves",
    "Outdoor lighting",
    "Trash and recycling bins",
    "Rock salt / ice melt"
  ]},
  { name: "Entryway / Mudroom", icon: "🚪", items: [
    "Key hooks or key bowl",
    "Shoe rack or mat",
    "Coat hooks or rack",
    "Umbrella stand",
    "Small bench or ottoman",
    "Mirror",
    "Mail organizer",
    "Doorstop",
    "Spare key copies",
    "Charging station for phones/devices"
  ]},
  { name: "Safety and Emergency", icon: "🛡️", items: [
    "Smoke detectors (one per floor + bedrooms)",
    "Carbon monoxide detectors",
    "Fire extinguisher (kitchen + garage)",
    "First aid kit (comprehensive)",
    "Emergency flashlight",
    "Spare batteries",
    "Emergency contact list (posted visible)",
    "Home fire escape plan",
    "Water shut-off valve location marked",
    "Backup power bank"
  ]},
  { name: "Home Maintenance", icon: "🏠", items: [
    "Plunger (kitchen + bathroom)",
    "Drain snake / hair clog tool",
    "Caulk + caulk gun",
    "Weather stripping",
    "Furnace filters (stock up, change quarterly)",
    "Touch-up paint (keep your wall color handy)",
    "Spackle and putty knife",
    "WD-40",
    "Duct tape",
    "Appliance manuals (keep in a binder)"
  ]}
];