// Gift note shown at the top of the wishlist
const GIFT_NOTE = "If I've listed a specific brand, that's my preference — but otherwise, feel free to choose whatever you think is best!";

const WISHLIST_ROOMS = [
  { name: "Kitchen", items: [
    { name: "Box grater",             icon: "grid-2x2",        url: "" },
    { name: "Microplane",             icon: "minus",           url: "" },
    { name: "Silicone Tongs",         icon: "grip",            url: "" },
    { name: "Slotted spoon",          icon: "utensils",        url: "" },
    { name: "Potato masher",          icon: "circle-dashed",   url: "" },
    { name: "Kitchen shears",         icon: "scissors",        url: "" },
    { name: "Dutch oven",             icon: "flame",           url: "" },
    { name: "Oven mitts (2 pairs)",   icon: "hand",            url: "" },
    { name: "Dish towels (6+)",       icon: "shirt",           url: "" },
    { name: "Blendtec blender",       icon: "zap",             url: "" },
  ]},
  { name: "Living Room", items: [
    { name: "Mesh wifi system",       icon: "wifi",            url: "" },
    { name: "Coasters",               icon: "circle",          url: "" },
    { name: "Wall art",               icon: "image",           url: "" },
    { name: "Clock",                  icon: "clock",           url: "" },
  ]},
  { name: "Bedroom", items: [
    { name: "Bed frame",              icon: "bed",             url: "" },
    { name: "Mattress",               icon: "bed-double",      url: "" },
    { name: "Mattress protector",     icon: "shield",          url: "" },
    { name: "Pillows (2 per person)", icon: "cloud",           url: "" },
    { name: "Pillowcases",            icon: "square",          url: "" },
    { name: "Flat sheet",             icon: "align-justify",   url: "" },
    { name: "Fitted sheet",           icon: "layout-grid",     url: "" },
    { name: "Duvet or comforter",     icon: "layers",          url: "" },
    { name: "Duvet cover",            icon: "layers-2",        url: "" },
    { name: "Extra blanket",          icon: "wind",            url: "" },
    { name: "Nightstands",            icon: "package",         url: "" },
    { name: "Nightstand lamp",        icon: "lamp",            url: "" },
    { name: "Dresser or chest of drawers", icon: "boxes",      url: "" },
    { name: "Full-length mirror",     icon: "scan",            url: "" },
    { name: "Extension cord with USB ports", icon: "plug",     url: "" },
  ]},
  { name: "Bathroom", items: [
    { name: "Bath mat",               icon: "square-dashed",   url: "" },
    { name: "Waterproof foot stool (for shower)", icon: "footprints", url: "" },
  ]},
  { name: "Home Office / Guest Room", items: [
    { name: "Desk chair (ergonomic)", icon: "armchair",        url: "" },
    { name: "Cable management clips", icon: "cable",           url: "" },
    { name: "Printer (used please)",  icon: "printer",         url: "" },
    { name: "Printer paper",          icon: "file",            url: "" },
    { name: "Ink cartridges",         icon: "droplets",        url: "" },
    { name: "Highlighters",           icon: "highlighter",     url: "" },
    { name: "Tape and dispenser",     icon: "tape",            url: "" },
    { name: "Stapler",                icon: "paperclip",       url: "" },
    { name: "Sticky notes",           icon: "sticky-note",     url: "" },
    { name: "Notepad",                icon: "notebook",        url: "" },
    { name: "Paper clips and binder clips", icon: "link",      url: "" },
    { name: "Power strip with USB",   icon: "plug-zap",        url: "" },
    { name: "Surge protector",        icon: "zap-off",         url: "" },
    { name: "Shredder",               icon: "scissors",        url: "" },
    { name: "Bookends",               icon: "book-open",       url: "" },
  ]},
  { name: "Garage / Storage", items: [
    { name: "Screwdriver set (flathead and Phillips)", icon: "screwdriver", url: "" },
    { name: "Power drill bit set",    icon: "drill",           url: "" },
    { name: "Level",                  icon: "ruler",           url: "" },
    { name: "Stud finder",            icon: "search",          url: "" },
    { name: "Utility knife",          icon: "pocket-knife",    url: "" },
    { name: "Adjustable wrench",      icon: "wrench",          url: "" },
    { name: "Pliers (needle-nose and regular)", icon: "grip-horizontal", url: "" },
    { name: "Hex key / Allen wrench set", icon: "hexagon",     url: "" },
    { name: "Rubber mallet",          icon: "hammer",          url: "" },
    { name: "Hand saw",               icon: "saw",             url: "" },
    { name: "Hacksaw",                icon: "minus-square",    url: "" },
    { name: "Pry bar",                icon: "bar-chart-2",     url: "" },
    { name: "Caulking gun",           icon: "pipette",         url: "" },
    { name: "Putty knife",            icon: "slice",           url: "" },
    { name: "Staple gun",             icon: "zap",             url: "" },
    { name: "Wire stripper",          icon: "cable",           url: "" },
    { name: "Voltage tester",         icon: "activity",        url: "" },
    { name: "Extension cord (big)",   icon: "plug",            url: "" },
    { name: "Ladder (6 ft step)",     icon: "align-vertical-justify-end", url: "" },
    { name: "Wheelbarrow",            icon: "shopping-cart",   url: "" },
    { name: "Shovel",                 icon: "shovel",          url: "" },
    { name: "Rake",                   icon: "combine",         url: "" },
    { name: "Broom (outdoor)",        icon: "brush",           url: "" },
    { name: "Snow shovel",            icon: "snowflake",       url: "" },
    { name: "Ice scraper",            icon: "wind",            url: "" },
    { name: "Garden hose and nozzle", icon: "droplets",        url: "" },
    { name: "Weed trimmer",           icon: "scissors",        url: "" },
    { name: "Leaf blower",            icon: "wind",            url: "" },
    { name: "Shop vacuum (wet/dry vac)", icon: "circle-dot",   url: "" },
    { name: "Workbench or table",     icon: "table",           url: "" },
    { name: "Wood glue",              icon: "droplet",         url: "" },
    { name: "Super glue",             icon: "droplet",         url: "" },
    { name: "Picture hanging hardware", icon: "frame",         url: "" },
    { name: "Toolbox",                icon: "briefcase",       url: "" },
    { name: "Storage bins with lids", icon: "archive",         url: "" },
    { name: "Label maker",            icon: "tag",             url: "" },
    { name: "Fire extinguisher",      icon: "fire-extinguisher", url: "" },
    { name: "First aid kit",          icon: "cross",           url: "" },
  ]},
  { name: "Laundry Room / Utility", items: [
    { name: "Stain remover stick (OxiClean gel stick only)", icon: "sparkles", url: "" },
    { name: "Drying rack",            icon: "git-branch",      url: "" },
    { name: "Iron",                   icon: "zap",             url: "" },
    { name: "Ironing board",          icon: "minus",           url: "" },
    { name: "Clothespins",            icon: "paperclip",       url: "" },
    { name: "Vacuum cleaner (canister vacuum)", icon: "loader-circle", url: "" },
  ]},
  { name: "Outdoor / Yard", items: [
    { name: "Kiddie pool",            icon: "waves",           url: "" },
    { name: "Outdoor furniture (table and chairs)", icon: "armchair", url: "" },
    { name: "Outdoor umbrella",       icon: "umbrella",        url: "" },
    { name: "Grill (gas)",            icon: "flame",           url: "" },
    { name: "Grill tools (tongs, brush, spatula)", icon: "utensils", url: "" },
    { name: "Grill cover",            icon: "shield",          url: "" },
    { name: "Propane",                icon: "fuel",            url: "" },
    { name: "Outdoor lighting",       icon: "sun",             url: "" },
    { name: "String lights",          icon: "lightbulb",       url: "" },
    { name: "Motion-sensor lights",   icon: "radar",           url: "" },
    { name: "Outdoor rug",            icon: "layout-grid",     url: "" },
  ]},
  { name: "Entryway / Mudroom", items: [
    { name: "Key hooks or key bowl",  icon: "key",             url: "" },
    { name: "Shoe rack and/or mat",   icon: "footprints",      url: "" },
    { name: "Coat hooks or rack",     icon: "anchor",          url: "" },
  ]},
];